version: '3'
services:
  backend-api:
    build:
      context: ./backend-api
    image: gm50x/backend-api:latest
    environment:
      PORT: 3000
    scale: 4
    networks:
      - skynet
  load-balancer:
    image: nginx:alpine
    ports:
      - 8000:80
    container_name: load-balancer
    volumes:
      - ./load-balancer/:/etc/nginx/conf.d/
    networks:
      - skynet
networks:
  skynet:
    driver: bridge