version: '3'
services:
  marco-api:
    build:
      context: ./marco-polo-api
    image: gm50x/marco-polo-api:latest
    environment:
      APP_NAME: 'MARCO'
      PORT: 3000
    container_name: marco-api
    networks:
      - skynet
  polo-api:
    build: 
      context: ./marco-polo-api
    image: gm50x/marco-polo-api:latest
    environment:
      APP_NAME: 'POLO'
      PORT: 3000
    container_name: polo-api
    networks:
      - skynet
  load-balancer:
    image: nginx:alpine
    ports:
      - 8000:80
    container_name: load-balancer
    volumes:
      - ./load-balancer/:/etc/nginx/conf.d/
    networks:
      - skynet
networks:
  skynet:
    driver: bridge